name: E2E Tests

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql:15.3.0
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: apisolid
        options: >-
          --health-cmd="pg_isready -U docker -d apisolid"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Start timer
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Restore NPM cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}-e2e
          restore-keys: |
            npm-

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid"

      - name: Calculate E2E duration and generate Summary
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "DURATION=$DURATION" >> $GITHUB_ENV
          MIN=$((DURATION/60))
          SEC=$((DURATION%60))
          echo "## 🚀 E2E Tests Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status | Duration |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|---------|" >> $GITHUB_STEP_SUMMARY
          echo "| E2E Tests | ${{ job.status }} | ${MIN}m ${SEC}s |" >> $GITHUB_STEP_SUMMARY
